{
 "title": "Prometheus SQS exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "queue", "label": "queue", "query": { "query": "label_values(queue)" } }
  ]
 },
 "panels": [
  {
   "title": "approximate_number_of_messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "approximate_number_of_messages{queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "approximate_number_of_messages_delayed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "approximate_number_of_messages_delayed{queue=~\"$queue\"}"
    }
   ]
  },
  {
   "title": "approximate_number_of_messages_not_visible",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "approximate_number_of_messages_not_visible{queue=~\"$queue\"}"
    }
   ]
  }
 ]
}